Repository Central-MakeUs/PeerNa-Web, pull requests merged in 2024-02, with the labels that each got.

#75 fix: 홈 페이지 및 동료페이지 쿼리 타입 수정
  src/components/common/molecule/ProfileListItem.tsx
  src/components/pages/home/molecule/UserProfileList.tsx
  src/components/pages/home/template/HomePage.tsx
  src/components/pages/moreFeedback/template/MoreFeedbackPage.tsx
  src/hooks/api/useGetMoreFeedback.tsx
  src/hooks/api/useGetSearchPeerPart.tsx
  src/hooks/api/useGetSearchPeerType.tsx
  src/utils/getTitleValue.ts
Labels: 🐞 bug

#80 feat: 카드 컴포넌트 추가
  src/assets/typeC.png
  src/assets/typeD.png
  src/assets/typeI.png
  src/assets/typeS.png
  src/components/common/atom/Card.tsx
  src/components/common/atom/ProgressTrack.tsx
  src/constants/card.ts
Labels: 💅 design

#78 feat: 동료 상세 프로젝트 api 추가
  src/assets/peerBg.png
  src/components/common/atom/AvatarButton.tsx
  src/components/common/molecule/Project.tsx
  src/components/common/organism/TopHeader.tsx
  src/components/pages/moreFeedback/template/MorePeerFeedbackPage.tsx
  src/components/pages/moreProject/molecule/PeerProjectInfo.tsx
  src/components/pages/moreProject/template/MorePeerProjectPage.tsx
  src/components/pages/moreProject/template/PeerProjectDetailPage.tsx
  src/components/pages/peerDetail/molecule/ProjectList.tsx
  src/components/pages/peerDetail/template/PeerDetailPage.tsx
  src/constants/activities.ts
  src/constants/images.ts
  src/hooks/api/useGetMorePeerFeedback.tsx
  src/hooks/api/useGetMorePeerProjectList.tsx
  src/hooks/api/useGetPeerDetail.tsx
  src/hooks/api/useGetPeerProjectInfo.tsx
  src/hooks/api/usePostPeerInviteProject.tsx
  tailwind.config.js
Labels: 🌟 feat

#82 feat: 알림 페이지 API 연동
  src/components/pages/moreProject/template/PeerProjectDetailPage.tsx
  src/components/pages/notification/molecule/EmptyNotification.tsx
  src/components/pages/notification/molecule/Notification.tsx
  src/components/pages/notification/molecule/NotificationType.tsx
  src/components/pages/notification/molecule/Project.tsx
  src/components/pages/notification/molecule/ProjectType.tsx
  src/components/pages/notification/organism/ProjectNotificationTab.tsx
  src/components/pages/notification/organism/ReviewNotificationTab.tsx
  src/components/pages/peerDetail/template/PeerDetailPage.tsx
  src/components/pages/project/organism/RecentProjectTab.tsx
  src/components/pages/projectDetail/organism/ProjectInformation.tsx
  src/components/pages/projectDetail/template/ProjectDetailPage.tsx
  src/components/pages/projectPropose/organism/CheckPropose.tsx
  src/components/pages/projectPropose/organism/DecidePropose.tsx
  src/components/pages/projectPropose/template/ProjectProposePage.tsx
  src/components/pages/reviewPeer/organism/WonderingMyCard.tsx
  src/constants/activities.ts
  src/constants/images.ts
  src/constants/noticeType.ts
  src/hooks/api/home/notice/useGetPeerReviewNotification.tsx
  src/hooks/api/home/notice/useGetProjectNotification.tsx
  src/hooks/api/project/[project-id]/usePostProjectRespondInvitation.ts
  src/hooks/api/project/useGetProjectById.tsx
  src/hooks/api/useGetMoreFeedback.tsx
  src/models/index.ts
  src/utils/date.ts
Labels: 🌟 feat

#94 feat: 카카오톡 공유하기 구현
  index.html
  src/App.tsx
  src/constants/index.ts
  src/hooks/common/useSendKakoMessage.tsx
  src/pages/home/index/atom/ReviewButton.tsx
  src/type/global.d.ts
  src/vite-env.d.ts
Labels: 🌟 feat

#97 feat: 에러 핸들링 추가 및 반응형 레이아웃 수정
  src/App.tsx
  src/assets/common/projectRequest.png
  src/assets/common/reviewRequest.png
  src/components/common/atom/PeerTalk.tsx
  src/components/common/molecule/ProfileListItem.tsx
  src/constants/images.ts
  src/hooks/api/home/notice/useGetProjectNotification.tsx
  src/hooks/api/home/peerId/useGetPeerDetail.tsx
  src/hooks/api/member/index/useGetMypageInfo.tsx
  src/hooks/api/member/index/usePostLogout.tsx
  src/hooks/api/member/index/usePostMemberInfo.tsx
  src/hooks/api/member/index/usePostMemberWithdrawal.tsx
  src/hooks/api/member/index/usePostPushAgree.tsx
  src/hooks/api/member/index/usePostReviewSelf.tsx
  src/hooks/api/member/mypage/usePatchMyProfile.tsx
  src/hooks/api/project/index/usePostCreateProject.tsx
  src/hooks/api/project/projectId/usePostPeerInviteProject.tsx
  src/hooks/api/project/projectId/usePostProjectRespondInvitation.ts
  src/hooks/api/review/index/usePostReviewPeer.tsx
  src/hooks/api/review/peerId/usePostRequestPeerTest.tsx
  src/hooks/common/useErrorHandler.tsx
  src/hooks/common/useHttpInterceptor.tsx
  src/hooks/common/useSendKakoMessage.tsx
  src/main.tsx
  src/pages/home/index/atom/EmptyData.tsx
  src/pages/home/index/atom/ReviewButton.tsx
  src/pages/home/index/molecule/UserProfileList.tsx
  src/pages/home/index/template/HomePage.tsx
  src/pages/mypage/index/molecule/CardTestResult.tsx
  src/pages/mypage/index/molecule/NoTestKeywordResult.tsx
  src/pages/mypage/index/template/MyPage.tsx
  src/pages/mypage/profileEdit/organism/ProfileEditList.tsx
  src/pages/mypage/profileEdit/template/ProfileEditPage.tsx
  src/pages/mypage/setting/molecule/SettingMenu.tsx
  src/pages/mypage/setting/template/SettingPage.tsx
  src/pages/peer/detail/atom/SelfTestResult.tsx
  src/pages/peer/detail/template/PeerDetailPage.tsx
  src/pages/peer/project/template/MyProjectListPage.tsx
  src/pages/peer/type/template/PeerTypePage.tsx
  src/utils/API.ts
Labels: 💚 refactor, 🌈 style

#106 feat: 프로젝트 참가 신청 수락/거부 기능 구현
  src/components/common/molecule/RadioTabs.tsx
  src/components/wrapper/Header.tsx
  src/constants/activities.ts
  src/hooks/api/project/projectId/requestJoin/usePostProjectRequestJoinAccept.tsx
  src/hooks/api/project/projectId/requestJoin/usePostProjectRequestJoinDecline.tsx
  src/hooks/store/useReviewState.tsx
  src/pages/home/index/molecule/UserProfileList.tsx
  src/pages/mypage/moreFeedback/template/MoreFeedbackPage.tsx
  src/pages/mypage/moreFeedback/template/MorePeerFeedbackPage.tsx
  src/pages/mypage/profileEdit/template/ProfileEditPage.tsx
  src/pages/mypage/setting/template/SettingPage.tsx
  src/pages/notification/index/molecule/ProjectType.tsx
  src/pages/notification/index/organism/ProjectNotificationTab.tsx
  src/pages/peer/detail/template/PeerDetailPage.tsx
  src/pages/peer/onboard/template/OnboardingPage.tsx
  src/pages/peer/project/template/MyProjectListPage.tsx
  src/pages/project/create/organism/ProjectForm.tsx
  src/pages/project/create/template/ProjectCreatePage.tsx
  src/pages/project/join/atom/JoinRequestAccept.tsx
  src/pages/project/join/atom/JoinRequestDecline.tsx
  src/pages/project/join/template/ProjectJoinPage.tsx
  src/pages/project/projectId/molecule/ProjectCreatorProfile.tsx
  src/pages/review/peer/organism/RequestInit.tsx
  src/store/reviewState.ts
  src/type/index.ts
Labels: 🌟 feat

#103 feat: 반응형으로 수정 및 모달 추가
  index.html
  src/assets/SpriteIcon.svg
  src/assets/common/home_bg.png
  src/assets/common/peer_detail_bg.png
  src/assets/icon/apple-icon-114x114.png
  src/assets/icon/apple-icon-120x120.png
  src/assets/icon/apple-icon-144x144.png
  src/assets/icon/apple-icon-152x152.png
  src/assets/icon/apple-icon-180x180.png
  src/assets/icon/apple-icon-57x57.png
  src/assets/icon/apple-icon-60x60.png
  src/assets/icon/apple-icon-72x72.png
  src/assets/icon/apple-icon-76x76.png
  src/assets/icon/favicon-16x16.png
  src/assets/icon/favicon-32x32.png
  src/assets/icon/favicon-96x96.png
  src/assets/icon/peerNa_logo.png
  src/assets/icon/peerna-logo.ico
  src/components/common/atom/AvatarButton.tsx
  src/components/common/atom/SvgIcon.tsx
  src/components/common/molecule/LegacyModal.tsx
  src/components/common/molecule/NoKeywordCard.tsx
  src/components/common/molecule/PeerRequestCompleteModal.tsx
  src/components/common/molecule/PeerVerifiyModal.tsx
  src/constants/icons.ts
  src/hooks/api/member/index/usePostPushAgree.tsx
  src/hooks/api/project/projectId/usePostProjectRespondInvitation.ts
  src/hooks/common/useErrorHandler.tsx
  src/hooks/common/useSendKakoMessage.tsx
  src/pages/home/index/atom/ReviewButton.tsx
  src/pages/home/index/template/HomePage.tsx
  src/pages/mypage/index/molecule/HeaderContainer.tsx
  src/pages/mypage/index/molecule/OverallScore.tsx
  src/pages/mypage/index/molecule/ProfileCard.tsx
  src/pages/mypage/index/organism/Layout.tsx
  src/pages/mypage/index/template/MyPage.tsx
  src/pages/mypage/profileEdit/template/ProfileEditPage.tsx
  src/pages/mypage/setting/molecule/SettingMenu.tsx
  src/pages/peer/detail/template/PeerDetailPage.tsx
  src/pages/peer/project/template/MyProjectListPage.tsx
  src/store/modal.ts
  src/type/index.ts
  tailwind.config.js
Labels: 🌟 feat, 🌈 style

#108 fix: build 시 발생되는 에러 해결
  index.html
  src/components/common/atom/ErrorToast.tsx
  src/components/common/atom/FlippableCard.tsx
  src/components/common/atom/PeerTalk.tsx
  src/components/common/molecule/ErrorModal.tsx
  src/components/common/molecule/Modals.tsx
  src/components/common/molecule/RequestListItem.tsx
  src/components/shadcn/toast.tsx
  src/components/shadcn/toaster.tsx
  src/components/shadcn/use-toast.tsx
  src/hooks/common/useHttpInterceptor.tsx
  src/pages/mypage/moreProject/molecule/PeerProjectInfo.tsx
  src/pages/mypage/profileEdit/template/ProfileEditPage.tsx
  src/store/modal.ts
  src/stories/common/atom/AvatarButton.stories.tsx
  src/stories/common/atom/Card.stories.tsx
  src/stories/common/atom/Chip.stories.tsx
  src/stories/common/atom/Dropdown.stories.tsx
  src/stories/common/atom/ErrorToast.stories.tsx
  src/stories/common/molecule/ProfileListItem.stories.tsx
  src/utils/API.ts
Labels: 🐞 bug

#109 fix: 홈에서 api 호출 문제 해결
  src/hooks/api/home/search/useGetSearchPeerPart.tsx
  src/hooks/api/member/index/useGetMe.tsx
  src/pages/home/index/atom/ReviewButton.tsx
  src/pages/home/index/template/HomePage.tsx
  src/pages/mypage/index/template/MyPage.tsx
Labels: 🐞 bug

#114 chore: 사용되지 않는 버튼 삭제 및 패딩값 추가
  src/pages/mypage/index/atom/SaveImageButton.tsx
  src/pages/mypage/index/molecule/Feedback.tsx
  src/pages/mypage/index/template/MyPage.tsx
Labels: 🔨 chore

#116 fix: 토큰 없을 경우 api 호출 제어
  src/hooks/api/home/search/useGetSearchPeerPart.tsx
  src/hooks/api/member/index/useGetMe.tsx
  src/pages/home/index/atom/ReviewButton.tsx
Labels: 🐞 bug

#117 fix: 테스트 도중 온보딩으로 이동하는 현상 수정
  src/pages/home/index/template/HomePage.tsx
  vercel.json
Labels: 🐞 bug

#121 style: 종합평가 마진값 수정
  src/pages/mypage/index/molecule/OverallOpinion.tsx
Labels: 🌈 style

#122 Dev
  src/pages/mypage/index/molecule/OverallOpinion.tsx
Labels: 🌈 style

#124 fix: 카카오 공유 시, 이미지 안보이는 현상 링크로 수정
  src/assets/common/projectRequest.png
  src/assets/common/reviewRequest.png
  src/constants/images.ts
  src/pages/home/index/atom/ReviewButton.tsx
  src/pages/mypage/index/template/MyPage.tsx
Labels: 🐞 bug

#126 fix: 바텀네비게이션 레이아웃 수정
  package.json
  src/assets/SpriteIcon.svg
  src/components/common/molecule/BottomNavigation.tsx
  src/pages/home/index/atom/ReviewButton.tsx
  vite.config.ts
  yarn.lock
Labels: 🐞 bug

#127 fix: 카카오톡 공유 이미지 url 수정
  src/hooks/common/useSendKakoMessage.tsx
  src/pages/home/index/atom/ReviewButton.tsx
  src/pages/mypage/index/template/MyPage.tsx
Labels: 🐞 bug

#129 fix: 프로필 수정에서 api 호출 안되는 문제 해결
  src/hooks/api/member/index/useGetMe.tsx
Labels: 🐞 bug

#132 feat: Notification탭에 페이지네이션 적용
  src/pages/notification/index/organism/ProjectNotificationTab.tsx
  src/pages/notification/index/organism/ReviewNotificationTab.tsx
  src/pages/notification/index/template/NotificationPage.tsx
  src/pages/project/index/organism/MyProject.tsx
  src/pages/project/index/organism/RecentProjectTab.tsx
  src/pages/project/index/template/ProjectPage.tsx
Labels: 🐞 bug, 🌟 feat

#140 fix: useGetMe 쿼리 에러 해결 및 tooltip 이슈
  src/hooks/api/member/index/useGetMe.tsx
  src/pages/mypage/index/atom/PeerToolTip.tsx
  src/pages/mypage/index/molecule/NoTestKeywordResult.tsx
  src/pages/mypage/index/molecule/OverallTestResult.tsx
Labels: 🐞 bug

#141 fix: notice 텍스트 수정
  src/pages/review/result/organism/ResultGuide.tsx
Labels: 🐞 bug

#147 Qa/#146
  src/components/common/atom/SelectListItem.tsx
  src/components/common/atom/TextInput.tsx
  src/hooks/api/member/index/usePostReviewSelf.tsx
  src/pages/peer/onboard/organism/OnboardingCard.tsx
  src/pages/project/projectId/organism/ProjectInformation.tsx
  src/pages/review/index/atom/ReviewCenterImage.tsx
  src/pages/review/index/organism/PeerType.tsx
  src/pages/review/result/organism/LoadingResult.tsx
  src/pages/review/result/organism/ResultShare.tsx
  src/pages/review/result/template/ReviewResultPage.tsx
Labels: 🐞 bug

#151 refactor: QA 사항 반영
  src/components/common/atom/PeerCard.tsx
  src/components/common/atom/PeerTalk.tsx
  src/components/common/molecule/NoKeywordCard.tsx
  src/components/common/molecule/PeerRequestCompleteModal.tsx
  src/components/common/molecule/PeerVerifiyModal.tsx
  src/components/common/molecule/ProfileListItem.tsx
  src/pages/home/index/organism/HomeBackground.tsx
  src/pages/home/index/template/HomePage.tsx
  src/pages/mypage/index/atom/PeerToolTip.tsx
  src/pages/mypage/index/atom/TotalScoreToolTip.tsx
  src/pages/mypage/index/molecule/OverallOpinion.tsx
  src/pages/mypage/index/molecule/OverallScore.tsx
  src/pages/mypage/index/molecule/OverallTestResult.tsx
  src/pages/peer/detail/molecule/ProjectList.tsx
Labels: 🐞 bug

#153 fix: LoadingResult 에러 수정
  src/constants/images.ts
  src/hooks/api/review/index/usePostUpdateMemberId.ts
  src/pages/auth/redirect/template/RedirectPage.tsx
  src/pages/developer/DeveloperPage.tsx
  src/pages/review/index/template/ReviewPage.tsx
  src/pages/review/result/organism/LoadingResult.tsx
  src/pages/review/result/organism/ResultShare.tsx
  src/utils/webview.ts
Labels: 🐞 bug

#155 fix: 프로필 이슈 해결
  src/components/common/molecule/ButtonContainer.tsx
  src/components/common/molecule/Modals.tsx
  src/components/common/molecule/ProfileListItem.tsx
  src/components/common/molecule/WithdrawalModal.tsx
  src/pages/home/index/template/HomePage.tsx
  src/pages/mypage/index/molecule/SelfTestModal.tsx
  src/pages/mypage/index/organism/CardContent.tsx
  src/pages/mypage/index/organism/KeywordContent.tsx
  src/pages/mypage/index/template/MyPage.tsx
  src/pages/mypage/setting/molecule/SettingMenu.tsx
  src/pages/mypage/setting/template/SettingPage.tsx
  src/pages/peer/detail/atom/PeerProfileCard.tsx
  src/pages/peer/detail/atom/PeerTestResult.tsx
  src/pages/peer/detail/atom/SelfTestResult.tsx
  src/pages/peer/detail/template/PeerDetailPage.tsx
  src/pages/peer/type/template/PeerTypePage.tsx
  src/store/modal.ts
Labels: 🐞 bug

#163 feat: 회원탈퇴 로직을 로그아웃과 같게 변경
  src/components/common/molecule/WithdrawalModal.tsx
Labels: 🐞 bug

#164 refactor: qa 반영
  src/constants/share.ts
  src/hooks/api/member/index/usePostMemberWithdrawal.tsx
  src/hooks/common/useSendKakoMessage.tsx
  src/hooks/common/useShareLink.tsx
  src/pages/home/index/atom/ReviewButton.tsx
  src/pages/mypage/index/atom/PeerToolTip.tsx
  src/pages/mypage/index/molecule/SelfTestModal.tsx
  src/pages/mypage/index/template/MyPage.tsx
  src/pages/project/projectId/template/ProjectDetailPage.tsx
  src/pages/review/result/molecule/ShareDrawer.tsx
Labels: 🐞 bug

#175 Qa/#156
  src/components/common/atom/Typography.tsx
  src/components/common/molecule/ProfileListItem.tsx
  src/constants/share.ts
  src/hooks/common/useShareLink.tsx
  src/pages/home/index/atom/ReviewButton.tsx
  src/pages/mypage/index/molecule/NoPeerTestResult.tsx
  src/pages/mypage/index/molecule/ProfileCard.tsx
  src/pages/mypage/index/organism/CardContent.tsx
  src/pages/mypage/index/template/MyPage.tsx
  src/pages/project/projectId/template/ProjectDetailPage.tsx
  src/pages/review/result/molecule/ShareDrawer.tsx
  src/pages/review/result/organism/ResultShare.tsx
Labels: 🐞 bug

#177 Qa/#170
  src/constants/images.ts
  src/pages/review/result/template/ReviewResultPage.tsx
Labels: 🐞 bug

#179 Qa/#170
  src/pages/review/result/organism/ResultShare.tsx
Labels: 🐞 bug

#183 Qa/#170
  src/assets/review/card/peer_bouvardia.png
  src/assets/review/card/peer_daisy.png
  src/assets/review/card/peer_mimosa.png
  src/assets/review/card/peer_violet.png
  src/assets/review/card/self_bouvardia.png
  src/assets/review/card/self_daisy.png
  src/assets/review/card/self_mimosa.png
  src/assets/review/card/self_violet.png
  src/components/common/atom/Picker.tsx
  src/components/common/atom/ProgressStep.tsx
  src/components/common/atom/ProgressTrack.tsx
  src/components/common/atom/SelectListItem.tsx
  src/components/common/atom/TextArea.tsx
  src/components/common/atom/TextInput.tsx
  src/components/common/molecule/UnderlineTabs.tsx
  src/components/wrapper/Header.tsx
  src/constants/localStorage.ts
  src/pages/mypage/moreProject/template/PeerProjectDetailPage.tsx
  src/pages/mypage/profileEdit/template/ProfileEditPage.tsx
  src/pages/mypage/setting/template/SettingPage.tsx
  src/pages/notification/index/molecule/EmptyNotification.tsx
  src/pages/notification/index/organism/ProjectNotificationTab.tsx
  src/pages/notification/index/organism/ReviewNotificationTab.tsx
  src/pages/notification/index/template/NotificationPage.tsx
  src/pages/peer/onboard/template/OnboardingPage.tsx
  src/pages/peer/project/template/MyProjectListPage.tsx
  src/pages/project/index/molecule/EmptyProject.tsx
  src/pages/project/index/organism/MyProject.tsx
  src/pages/project/join/template/ProjectJoinPage.tsx
  src/pages/project/projectId/template/ProjectDetailPage.tsx
  src/pages/project/propose/organism/CheckPropose.tsx
  src/pages/project/propose/organism/DecidePropose.tsx
  src/pages/review/index/molecule/ReviewHeader.tsx
  src/pages/review/index/organism/PeerType.tsx
  src/pages/review/index/template/ReviewPage.tsx
  src/pages/review/peer/organism/GuessWhoResponse.tsx
  src/pages/review/peer/organism/InputProjectDate.tsx
  src/pages/review/peer/organism/IntroPeerReview.tsx
  src/pages/review/peer/organism/IsOffendedResponse.tsx
  src/pages/review/peer/organism/OverDate.tsx
  src/pages/review/peer/organism/RequestInit.tsx
  src/pages/review/peer/organism/ThanksReview.tsx
  src/pages/review/peer/organism/WonderingMyCard.tsx
  src/pages/review/result/organism/AnalyzePeerCard.tsx
  src/pages/review/result/organism/ResultGuide.tsx
  src/pages/review/result/organism/ResultShare.tsx
  src/pages/review/self/organism/InputName.tsx
  src/pages/review/self/organism/SelectJob.tsx
  src/pages/review/self/organism/SelectPosition.tsx
  src/pages/review/self/template/ReviewSelfPage.tsx
  src/utils/index.ts
  src/utils/webview.ts
Labels: 🐞 bug

#185 fix: ResultShare 헤더 클릭 안되는 버그 수정
  src/components/wrapper/Header.tsx
  src/pages/review/result/organism/ResultShare.tsx
Labels: 🐞 bug

#187 refactor: qa 반영
  src/assets/SpriteIcon.svg
  src/constants/icons.ts
  src/constants/share.ts
  src/pages/home/index/atom/ReviewButton.tsx
  src/pages/home/index/molecule/UserProfileList.tsx
  src/pages/home/index/template/HomePage.tsx
  src/pages/mypage/index/atom/PeerToolTip.tsx
  src/pages/mypage/index/atom/TotalScoreToolTip.tsx
  src/pages/mypage/index/organism/CardContent.tsx
  src/pages/peer/detail/atom/PeerProfileCard.tsx
  src/pages/peer/type/template/PeerTypePage.tsx
Labels: 🐞 bug

#195 Qa/#188
  src/components/common/atom/TextInput.tsx
  src/components/common/molecule/UnderlineTabs.tsx
  src/components/wrapper/AppScreenContainter.tsx
  src/constants/images.ts
  src/constants/localStorage.ts
  src/hooks/common/useHistory.tsx
  src/pages/home/index/template/HomePage.tsx
  src/pages/mypage/index/molecule/SelfTestModal.tsx
  src/pages/notification/index/template/NotificationPage.tsx
  src/pages/peer/onboard/organism/OnboardingCard.tsx
  src/pages/project/index/organism/RecentProjectTab.tsx
  src/pages/project/index/template/ProjectPage.tsx
  src/pages/review/result/organism/AnimationCards.tsx
  src/pages/review/self/template/ReviewSelfPage.tsx
  src/utils/index.ts
  src/utils/webview.ts
Labels: 🐞 bug

#198 프로젝트 제안 모달 버그 수정
  src/components/common/molecule/Modals.tsx
  src/components/common/molecule/ProjectJoinRequestModal.tsx
  src/pages/project/projectId/template/ProjectDetailPage.tsx
Labels: 🐞 bug

#200 fix: 링크가 없는 경우에 보이지 않도록 수정
  src/pages/project/projectId/organism/ProjectInformation.tsx
Labels: 🐞 bug

#203 style: 프로젝트 리스트 수정
  src/pages/mypage/moreProject/molecule/PeerProjectInfo.tsx
  src/pages/mypage/moreProject/template/PeerProjectDetailPage.tsx
  src/pages/peer/detail/template/PeerDetailPage.tsx
  src/pages/peer/project/template/MyProjectListPage.tsx
Labels: 🐞 bug

#205 style: 레이아웃 수정
  src/components/common/molecule/ProfileListItem.tsx
  src/pages/mypage/index/atom/PeerToolTip.tsx
  src/pages/mypage/index/atom/TotalScoreToolTip.tsx
  src/pages/mypage/index/molecule/NoTestKeywordResult.tsx
  src/pages/mypage/index/molecule/OverallTestResult.tsx
  src/pages/peer/project/template/MyProjectListPage.tsx
Labels: 🐞 bug

#207 refactor: 버튼 focus 스타일 수정 및 이미지 링크 추가
  index.html
  src/components/common/atom/Button.tsx
  src/utils/image.ts
Labels: 🐞 bug

#209 refactor: 링크에 따른 메타 생성
  index.html
  src/utils/image.ts
Labels: 🐞 bug

#211 fix: 링크 공유 url 수정
  src/utils/image.ts
Labels: 🐞 bug

#213 refactor: 클립 보드 데이터 읽기로 url 수정
  src/utils/image.ts
Labels: 🐞 bug

#215 feat: 탈퇴, 중복 리뷰 방지
  src/components/common/atom/TextArea.tsx
  src/components/common/molecule/AlreadyReviewModal.tsx
  src/components/common/molecule/Modals.tsx
  src/components/common/molecule/WithdrawalModal.tsx
  src/hooks/api/member/index/usePostMemberWithdrawal.tsx
  src/hooks/api/review/index/usePostPeerReviewReject.tsx
  src/hooks/store/useReviewHistory.tsx
  src/pages/notification/index/molecule/NotificationType.tsx
  src/pages/notification/index/organism/ReviewNotificationTab.tsx
  src/pages/review/index/template/ReviewPage.tsx
  src/pages/review/peer/organism/InputProjectDate.tsx
  src/pages/review/peer/organism/RequestInit.tsx
  src/pages/review/self/template/ReviewSelfPage.tsx
  src/store/modal.ts
  src/store/reviewHistory.ts
  src/type/index.ts
Labels: 🐞 bug

#217 refactor: 이미지 url 수정 및 스타일 수정
  index.html
  src/constants/share.ts
  src/pages/home/index/molecule/UserProfileList.tsx
  src/pages/home/index/template/HomePage.tsx
  src/pages/mypage/index/template/MyPage.tsx
  src/pages/peer/project/template/MyProjectListPage.tsx
  src/pages/review/result/molecule/ShareDrawer.tsx
  src/utils/image.ts
Labels: 🐞 bug

#219 style: ShareDrawer z-index 추가
  src/pages/review/result/molecule/ShareDrawer.tsx
  src/pages/review/result/organism/ResultShare.tsx
Labels: 💅 design

#221 fix: 종합 점수 및 프로필 수정 이슈 해결
  src/components/common/atom/AvatarButton.tsx
  src/components/common/atom/Dropdown.tsx
  src/components/common/atom/PeerCard.tsx
  src/components/common/molecule/ProfileListItem.tsx
  src/constants/share.ts
  src/hooks/api/member/mypage/usePatchMyProfile.tsx
  src/pages/home/index/molecule/UserProfileList.tsx
  src/pages/home/index/organism/HomeBackground.tsx
  src/pages/mypage/index/organism/KeywordContent.tsx
  src/pages/mypage/profileEdit/molecule/JobDrawer.tsx
  src/pages/mypage/profileEdit/molecule/PosititonDrawer.tsx
  src/pages/mypage/profileEdit/molecule/SelectListItem.tsx
  src/pages/notification/index/molecule/HomeHeader.tsx
  src/pages/peer/detail/organism/PeerKeywordContent.tsx
Labels: 🐞 bug

#223 QA 수정 사항 반영
  src/App.tsx
  src/components/common/molecule/ProjectInviteModal.tsx
  src/components/wrapper/Content.tsx
  src/hooks/api/project/projectId/usePostPeerInviteProject.tsx
  src/hooks/api/review/peerId/usePostRequestPeerTest.tsx
  src/pages/mypage/moreProject/template/PeerProjectDetailPage.tsx
  src/pages/review/peer/organism/WonderingMyCard.tsx
  src/pages/review/peer/template/ReviewPeerPage.tsx
  src/pages/review/result/molecule/Card.tsx
  src/pages/review/result/organism/AnimationCards.tsx
  src/pages/review/result/organism/ResultLoginRequired.tsx
Labels: 🐞 bug

#225 style: style 속성으로 background image css 작성
  src/pages/home/index/organism/HomeBackground.tsx
Labels: 🐞 bug

#231 refactor: 홈 이미지 수정 및 불필요한 코드 삭제
  src/constants/images.ts
  src/pages/home/index/molecule/UserProfileList.tsx
  src/pages/home/index/template/HomePage.tsx
  src/pages/peer/project/template/MyProjectListPage.tsx
Labels: 🐞 bug

#234 feat: gtm 라이브러리 추가 설정
  index.html
  package.json
  src/main.tsx
  yarn.lock
Labels: 🌟 feat
