Repository Central-MakeUs/PeerNa-Web, pull requests merged in 2024-01, with the labels that each got.

#5 feat: design system 반영 #3
  .storybook/main.ts
  .storybook/preview.ts
  index.html
  package.json
  src/components/common/atom/Typography.tsx
  src/constants/styles.ts
  src/index.css
  src/main.tsx
  src/stories/atom/Typography.stories.tsx
  src/types/styles.ts
  tailwind.config.js
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: 🌟 feat

#7 feat: 공통 컴포넌트 - Input, Textarea, Picker
  .eslintrc.cjs
  package.json
  src/assets/icons/calendar.svg
  src/assets/icons/clear.svg
  src/components/common/molecule/Picker.tsx
  src/components/common/molecule/TextArea.tsx
  src/components/common/molecule/TextInput.tsx
  src/constants/styles.ts
  src/stories/molecule/Picker.stories.tsx
  src/stories/molecule/TextArea.stories.tsx
  src/stories/molecule/TextInput.stories.tsx
  src/types/styles.ts
  src/vite-env.d.ts
  svg.d.ts
  tailwind.config.js
  tsconfig.json
  vite.config.ts
Labels: 🌟 feat

#8 feat: design system/#3
  .eslintrc.cjs
  .storybook/preview.ts
  package.json
  src/App.tsx
  src/assets/icons/Alert.svg
  src/assets/icons/Alert_Fill.svg
  src/assets/icons/Clipboard.svg
  src/assets/icons/Clipboard_Fill.svg
  src/assets/icons/Contact.svg
  src/assets/icons/Contact_Fill.svg
  src/assets/icons/Home.svg
  src/assets/icons/Home_Fill.svg
  src/assets/icons/People.svg
  src/assets/icons/People_Fill.svg
  src/assets/icons/iOSRightArrow.svg
  src/assets/icons/index.tsx
  src/components/common/atom/Button.tsx
  src/components/common/atom/Picker.tsx
  src/components/common/atom/StackFlow.tsx
  src/components/common/atom/TabItem.tsx
  src/components/common/atom/TextArea.tsx
  src/components/common/atom/TextInput.tsx
  src/components/common/atom/Toggle.tsx
  src/components/common/atom/Typography.tsx
  src/components/common/molecule/BottomNavigation.tsx
  src/components/common/molecule/ButtonContainer.tsx
  src/components/common/molecule/Picker.tsx
  src/components/common/molecule/TextArea.tsx
  src/components/common/molecule/TextInput.tsx
  src/components/template/Home.tsx
  src/components/template/Mypage.tsx
  src/components/template/Notification.tsx
  src/components/template/Peer.tsx
  src/components/template/Project.tsx
  src/constants/activities.ts
  src/constants/styles.ts
  src/constants/trash.ts
  src/main.tsx
  src/stories/.gitkeep
  src/stories/atom/Button.stories.tsx
  src/stories/atom/Picker.stories.tsx
  src/stories/atom/TextArea.stories.tsx
  src/stories/atom/TextInput.stories.tsx
  src/stories/atom/Toggle.stories.tsx
  src/stories/atom/Typography.stories.tsx
  src/stories/molecule/BottomNavigation.stories.tsx
  src/stories/molecule/ButtonContainer.stories.tsx
  src/svg.d.ts
  src/type/activities.ts
  src/type/styles.ts
  tailwind.config.js
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: 🌟 feat

#10 feat: shadcn-ui 적용 및 BottomSheet 구현 #9
  .storybook/preview.tsx
  components.json
  package.json
  src/components/common/molecule/BottomNavigation.tsx
  src/components/common/molecule/BottomSheet.tsx
  src/components/ui/drawer.tsx
  src/constants/styles.ts
  src/index.css
  src/main.tsx
  src/store/bottomSheet.ts
  src/stories/molecule/BottomSheet.stories.tsx
  src/utils/shadcn.ts
  tailwind.config.js
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: 🌟 feat

#11 feat: Svg Sprite 및 Progressbar 컴포넌트화
  package.json
  src/assets/SpriteIcon.svg
  src/assets/SvgIcon.tsx
  src/components/common/atom/ProgressStep.tsx
  src/components/common/atom/ProgressTrack.tsx
  src/components/common/atom/TabItem.tsx
  src/components/common/molecule/ProgressBar.tsx
  src/constants/icons.ts
  src/stories/atom/ProgressStep.stories.tsx
  src/stories/atom/ProgressTrack.stories.tsx
  src/stories/atom/SvgIcon.stories.tsx
  src/stories/molecule/ProgressBar.stories.tsx
  src/svg.d.ts
  src/vite-env.d.ts
  vite.config.ts
Labels: 🌟 feat

#13 fix: ProgressBar 컴포넌트 스토리북 오류 해결
  src/components/common/molecule/ProgressBar.tsx
Labels: 🐞 bug

#14 feat, fix: Modal, Header 컴포넌트 구현 및 스토리북 에러 해결
  src/assets/SpriteIcon.svg
  src/assets/SvgIcon.tsx
  src/components/common/atom/IconButton.tsx
  src/components/common/atom/ProgressStep.tsx
  src/components/common/atom/ProgressTrack.tsx
  src/components/common/atom/Typography.tsx
  src/components/common/molecule/Modal.tsx
  src/components/common/molecule/ProgressBar.tsx
  src/components/common/organism/Header.tsx
  src/constants/icons.ts
  src/store/modal.ts
  src/stories/atom/ProgressStep.stories.tsx
  src/stories/atom/ProgressTrack.stories.tsx
  src/stories/molecule/Modal.stories.tsx
  src/stories/molecule/ProgressBar.stories.tsx
  src/stories/organism/Header.stories.tsx
  tsconfig.json
Labels: 🐞 bug, 🌟 feat

#12 Feat/design system/#3
  .storybook/preview-head.html
  src/assets/SpriteIcon.svg
  src/assets/SvgIcon.tsx
  src/assets/icons/Color.svg
  src/assets/icons/ColorLine.svg
  src/assets/icons/Connected.svg
  src/assets/icons/PersonRibbon.svg
  src/assets/icons/TaskList.svg
  src/assets/icons/index.tsx
  src/components/common/atom/Badge.tsx
  src/components/common/atom/Button.tsx
  src/components/common/atom/Chip.tsx
  src/components/common/atom/Slider.tsx
  src/components/common/atom/Spinner.tsx
  src/components/common/atom/Step.tsx
  src/components/common/atom/TextArea.tsx
  src/components/common/atom/TextInput.tsx
  src/components/common/atom/Tooltip.tsx
  src/components/common/molecule/BottomSheet.tsx
  src/components/common/molecule/KeywordCard.tsx
  src/components/common/molecule/RadioTabs.tsx
  src/components/common/molecule/UnderlineTabs.tsx
  src/constants/icons.ts
  src/constants/styles.ts
  src/constants/trash.ts
  src/index.css
  src/stories/atom/AllIcons.stories.tsx
  src/stories/atom/Badge.stories.tsx
  src/stories/atom/Chip.stories.tsx
  src/stories/atom/Slider.stories.tsx
  src/stories/atom/Spinner.stories.tsx
  src/stories/atom/Step.stories.tsx
  src/stories/atom/SvgIcon.stories.tsx
  src/stories/atom/Tooltip.stories.tsx
  src/stories/molecule/KeywordCard.stories.tsx
  src/stories/molecule/RadioTabs.stories.tsx
  src/stories/molecule/UnderlineTabs.stories.tsx
  src/utils/styles.tsx
Labels: 🌟 feat

#16 feat: Project, Profile, Request 리스트 아이템 구현
  src/assets/SpriteIcon.svg
  src/assets/icons/Alert.svg
  src/assets/icons/Alert_Fill.svg
  src/assets/icons/Clipboard.svg
  src/assets/icons/Clipboard_Fill.svg
  src/assets/icons/Color.svg
  src/assets/icons/ColorLine.svg
  src/assets/icons/Connected.svg
  src/assets/icons/Contact.svg
  src/assets/icons/Contact_Fill.svg
  src/assets/icons/Home.svg
  src/assets/icons/Home_Fill.svg
  src/assets/icons/People.svg
  src/assets/icons/People_Fill.svg
  src/assets/icons/PersonRibbon.svg
  src/assets/icons/TaskList.svg
  src/assets/icons/calendar.svg
  src/assets/icons/clear.svg
  src/assets/icons/iOSRightArrow.svg
  src/assets/icons/index.tsx
  src/components/common/atom/AlarmListItem.tsx
  src/components/common/atom/Button.tsx
  src/components/common/atom/IconButton.tsx
  src/components/common/atom/ProfileListItem.tsx
  src/components/common/atom/ProjectListItem.tsx
  src/components/common/atom/RequestListItem.tsx
  src/components/common/atom/TabItem.tsx
  src/components/common/atom/TextArea.tsx
  src/components/common/atom/TextInput.tsx
  src/components/common/atom/Typography.tsx
  src/components/common/molecule/ButtonContainer.tsx
  src/components/common/molecule/Project.tsx
  src/constants/icons.ts
  src/stories/atom/Alarm.stories.tsx
  src/stories/atom/ProfileListItem.stories.tsx
  src/stories/atom/ProjectListItem.stories.tsx
  src/stories/atom/RequestListItem.stories.tsx
  src/stories/molecule/Project.stories.tsx
Labels: 🌟 feat

#15 fix: SvgIcon 기존 컬러값에 의해 안보이는 문제 해결 및 스타일 코드 추가
  package.json
  src/assets/SpriteIcon.svg
  src/components/common/atom/Typography.tsx
  src/components/common/molecule/Dropdown.tsx
  src/components/common/organism/Header.tsx
  src/components/ui/select.tsx
  src/constants/icons.ts
  src/stories/atom/ProgressStep.stories.tsx
  src/stories/molecule/Dropdown.stories.tsx
  src/stories/molecule/Modal.stories.tsx
  src/stories/organism/Header.stories.tsx
Labels: 🐞 bug

#18 feat: api(axios) 기본 설정 및 에러 핸들링 기본 설정
  .gitignore
  package.json
  src/apis/common/index.ts
  src/apis/index.ts
  src/main.tsx
  src/vite-env.d.ts
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: 🌟 feat

#19 feat: 컴포넌트 구조 변경 및 공통 컴포넌트 구현
  package.json
  src/assets/SpriteIcon.svg
  src/components/common/atom/AlarmListItem.tsx
  src/components/common/atom/AvatarButton.tsx
  src/components/common/atom/Chip.tsx
  src/components/common/atom/DatePicker.tsx
  src/components/common/atom/FullBleed.tsx
  src/components/common/atom/IconButton.tsx
  src/components/common/atom/ProfileListItem.tsx
  src/components/common/atom/ProgressTrack.tsx
  src/components/common/atom/RequestListItem.tsx
  src/components/common/atom/SvgIcon.tsx
  src/components/common/atom/TabItem.tsx
  src/components/common/atom/Typography.tsx
  src/components/common/atom/calendar.tsx
  src/components/common/atom/calendarButton.tsx
  src/components/common/atom/drawer.tsx
  src/components/common/atom/popover.tsx
  src/components/common/atom/select.tsx
  src/components/common/molecule/BottomSheet.tsx
  src/components/common/molecule/Dropdown.tsx
  src/components/common/molecule/KeywordCard.tsx
  src/components/common/molecule/ProgressBar.tsx
  src/components/common/molecule/Project.tsx
  src/components/common/organism/Header.tsx
  src/constants/icons.ts
  src/stories/atom/AllIcons.stories.tsx
  src/stories/atom/AvatarButton.stories.tsx
  src/stories/atom/DatePicker.stories.tsx
  src/stories/atom/FullBleed.stories.tsx
  src/stories/atom/ProgressStep.stories.tsx
  src/stories/atom/ProjectListItem.stories.tsx
  src/stories/atom/SvgIcon.stories.tsx
  tailwind.config.js
Labels: 🌟 feat

#29 feat: 카카오 로그인 구현
  package.json
  src/apis/auth.ts
  src/components/common/atom/TabItem.tsx
  src/components/common/molecule/BottomNavigation.tsx
  src/components/common/molecule/Modal.tsx
  src/components/login/organism/LoginModal.tsx
  src/components/login/template/Redirect.tsx
  src/components/peer/template/Peer.tsx
  src/constants/activities.ts
  src/constants/localStorage.ts
  src/hooks/useModal.tsx
  src/hooks/useStackFlow.tsx
  src/hooks/useToken.tsx
  src/store/modal.ts
Labels: 🌟 feat

#31 Feat/vite version update/#30
  package.json
  yarn.lock
Labels: 🐞 bug, 💚 refactor

#38 bug: 동료 리뷰 페이지에서 날짜 문자열 NaN 나오는 현상 수정
  src/components/pages/peerReview/organism/InputProjectDate.tsx
  src/components/pages/peerReview/organism/IntroPeerReview.tsx
  src/components/pages/peerReview/organism/ThanksReview.tsx
  src/components/pages/peerReview/template/PeerReviewPage.tsx
Labels: 🐞 bug

#39 style: DatePicker width를 flex-1로 수정
  src/components/common/atom/DatePicker.tsx
  src/components/pages/peerReview/organism/InputProjectDate.tsx
Labels: 🌈 style

#49 feat: accessToken 웹 앱 통신을 통한 자동 로그인 구현
  package.json
  src/App.tsx
  src/apis/index.ts
  src/components/common/molecule/BottomNavigation.tsx
  src/components/common/organism/Header.tsx
  src/components/pages/login/template/RedirectPage.tsx
  src/components/pages/mypage/template/MyPage.tsx
  src/components/pages/review/template/ReviewPage.tsx
  src/components/pages/reviewResult/molecule/ShareDrawer.tsx
  src/components/pages/reviewResult/organism/LoadingResult.tsx
  src/components/pages/reviewResult/organism/ResultLoginRequired.tsx
  src/components/pages/reviewResult/template/ReviewResultPage.tsx
  src/components/wrapper/AppScreenContainter.tsx
  src/components/wrapper/FixedBottomButton.tsx
  src/components/wrapper/FixedButtonContainer.tsx
  src/components/wrapper/PageContainer.tsx
  src/hooks/useHistory.tsx
  src/hooks/useModal.tsx
  src/hooks/useToken.tsx
  src/store/history.ts
  src/store/recoilPersist.ts
  src/type/global.d.ts
  src/utils/styles.ts
  src/utils/token.ts
  src/utils/webview.ts
  yarn.lock
Labels: 🌟 feat

#46 feat: 동료들에게 나는 어떤 동료일까요? 테스트 부분 이미지 및 PeerType 수정
  src/assets/SpriteIcon.svg
  src/components/pages/review/atom/ReviewCenterImage.tsx
  src/components/pages/review/molecule/ReviewCenterImage.tsx
  src/components/pages/review/organism/PeerType.tsx
  src/constants/icons.ts
  src/constants/images.ts
  src/constants/peerType.ts
  src/store/reviewState.ts
Labels: 🌟 feat

#53 feat: apple login 구현
  index.html
  package.json
  src/App.tsx
  src/assets/SpriteIcon.svg
  src/components/common/atom/AppleLogin.tsx
  src/components/pages/home/template/HomePage.tsx
  src/components/pages/login/template/AppleRedirectPage.tsx
  src/components/pages/login/template/KakaoRedirectPage.tsx
  src/components/pages/review/template/ReviewPage.tsx
  src/constants/activities.ts
  src/constants/icons.ts
  src/type/apple.d.ts
  yarn.lock
Labels: 🌟 feat

#60 design: 알림 페이지 레이아웃 구현
  index.html
  package.json
  src/assets/SpriteIcon.svg
  src/components/common/atom/Typography.tsx
  src/components/common/molecule/AlarmListItem.tsx
  src/components/common/molecule/BottomNavigation.tsx
  src/components/common/molecule/ErrorModal.tsx
  src/components/common/molecule/Modal.tsx
  src/components/common/molecule/NavigationHeader.tsx
  src/components/common/molecule/Project.tsx
  src/components/pages/mypage/template/MyPage.tsx
  src/components/pages/notification/molecule/Notification.tsx
  src/components/pages/notification/molecule/NotificationType.tsx
  src/components/pages/notification/molecule/Project.tsx
  src/components/pages/notification/molecule/ProjectType.tsx
  src/components/pages/notification/organism/ProjectNotificationTab.tsx
  src/components/pages/notification/organism/ReviewNotificationTab.tsx
  src/components/pages/notification/template/NotificationPage.tsx
  src/components/pages/project/organism/MyProject.tsx
  src/components/pages/project/organism/RecentProjectTab.tsx
  src/components/pages/project/template/ProjectPage.tsx
  src/components/pages/projectCreate/organism/ProjectForm.tsx
  src/components/pages/projectCreate/template/ProjectCreatePage.tsx
  src/components/pages/projectDetail/organism/ProjectInformation.tsx
  src/components/pages/projectDetail/template/ProjectDetailPage.tsx
  src/components/pages/projectPropose/organism/CheckPropose.tsx
  src/components/pages/projectPropose/organism/DecidePropose.tsx
  src/components/pages/projectPropose/template/ProjectProposePage.tsx
  src/components/pages/reviewResult/molecule/ShareDrawer.tsx
  src/components/pages/reviewResult/organism/ResultShare.tsx
  src/components/wrapper/FixedBottomButton.tsx
  src/components/wrapper/FixedButtonContainer.tsx
  src/components/wrapper/ListItemContainer.tsx
  src/constants/activities.ts
  src/constants/icons.ts
  src/hooks/useStackFlow.tsx
  src/main.tsx
  src/utils/SingleChildPortal.tsx
  yarn.lock
Labels: 💅 design

#69 Hotfix/#68
  index.html
  src/App.tsx
  src/apis/common/index.ts
  src/components/common/molecule/AlarmListItem.tsx
  src/components/common/molecule/BottomNavigation.tsx
  src/components/pages/home/template/HomePage.tsx
  src/components/pages/login/template/AppleRedirectPage.tsx
  src/components/pages/login/template/KakaoRedirectPage.tsx
  src/components/pages/moreFeedback/template/MoreFeedbackPage.tsx
  src/components/pages/mypage/molecule/SelfTestResult.tsx
  src/components/pages/mypage/template/MyPage.tsx
  src/components/pages/notification/template/NotificationPage.tsx
  src/components/pages/profileEdit/organism/ProfileEditList.tsx
  src/components/pages/profileEdit/template/ProfileEditPage.tsx
  src/components/pages/project/organism/RecentProjectTab.tsx
  src/components/pages/reviewResult/organism/ResultShare.tsx
  src/components/pages/setting/template/SettingPage.tsx
  src/components/wrapper/FixedBottomButton.tsx
  src/constants/image.ts
  src/constants/localStorage.ts
  src/hooks/api/project/useGetProjectList.tsx
  src/hooks/api/useGetMe.tsx
  src/hooks/api/useGetSearchPeerType.tsx
  src/utils/token.ts
  src/utils/webview.ts
  src/vite-env.d.ts
Labels: 🐞 bug
